language: go

# Install glide
addons:
  apt:
    sources:
    - sourceline: 'ppa:masterminds/glide'
    packages:
    - glide

cache:
  directories:
    - vendor/

install:
  - make setup

script:
  - make test-ci
  - make build-all
